export const Types = {
    TOGGLE_PLAY: 'TOGGLE_PLAY',
    NEXT_SONG: 'NEXT_SONG',
    PREV_SONG: 'PREV_SONG',
    ADD_SONG: 'ADD_SONG',
    CHANGE_SONG: 'CHANGE_SONG',
    CHANGE_ALBUM: 'CHANGE_ALBUM'
};
